In [1]:
import os
import datetime

import IPython
import IPython.display
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

#custom functions import
from ts_functions import time_window_generator
from aux_functions import aux_functions


mpl.rcParams['figure.figsize'] = (8, 6)
mpl.rcParams['axes.grid'] = False

## Display File 1

In [2]:
display_file = "training_log/sm_ma_gc.csv"

fileDir = os.path.dirname(os.path.realpath('__file__'))
filename = os.path.join(fileDir, display_file)
df = pd.read_csv(filename)

In [13]:
display(df[:60])

,stock_code,Average MAPE of val data_set,Average MAPE of test data_set,Iteration_number,Training data_set size,Validation data_set size,testing data_set size,model_name,(data with sma5,ema5,ema20,ema50,ema_20_50_gc)
0,000001.SZ,19.101615,94.243288,10,3497,749,750,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
1,000002.SZ,4.377207,4.453357,10,3497,749,750,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
2,000008.SZ,15.383230,8.146482,10,3405,730,730,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
3,000001.SZ,43.858890,45.516707,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
4,000002.SZ,4.015493,4.286637,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
5,000008.SZ,17.120712,11.913242,10,3405,973,487,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
6,000009.SZ,18.728840,27.879832,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
7,000027.SZ,3.720398,29.768674,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
8,000039.SZ,39.731648,52.106204,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
9,000046.SZ,46.901301,5.101535,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
10,000060.SZ,27.643286,4.795263,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
11,000061.SZ,41.529056,3.465517,10,3471,992,496,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
12,000063.SZ,9.303211,14.353666,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
13,000066.SZ,43.241756,10.013061,10,3455,987,494,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
14,000069.SZ,4.645981,4.552321,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
15,000100.SZ,18.134371,3.671896,10,2912,831,417,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
16,000156.SZ,3.762877,2.425920,10,2422,691,347,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
17,000157.SZ,2.552354,9.624212,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
18,000166.SZ,5.303641,2.948061,10,1269,362,182,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
19,000301.SZ,48.625135,16.060417,10,3461,989,495,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
20,000333.SZ,10.354332,5.784250,10,1476,422,211,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
21,000338.SZ,3.027393,4.655938,10,2564,732,367,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
22,000400.SZ,58.999656,24.821413,10,3479,994,497,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
23,000402.SZ,46.349469,2.715840,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
24,000408.SZ,40.891602,20.434814,10,3329,952,476,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
25,000413.SZ,8.402441,4.039873,10,3485,996,498,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
26,000415.SZ,25.818130,2.478163,10,3161,903,452,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
27,000423.SZ,6.017474,3.426098,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
28,000425.SZ,2.491817,3.279653,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
29,000503.SZ,32.788438,13.913050,10,3448,985,493,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
30,000538.SZ,2.514538,4.123022,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
31,000539.SZ,2.910443,3.478213,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
32,000540.SZ,41.016544,2.794401,10,3291,940,471,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
33,000553.SZ,9.293765,84.882889,10,3364,961,481,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
34,000555.SZ,79.038518,58.817685,10,3309,946,473,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
35,000559.SZ,12.212175,3.194660,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
36,000568.SZ,4.229615,61.498143,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
37,000581.SZ,46.211809,21.400017,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
38,000596.SZ,5.378792,49.471336,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
39,000598.SZ,3.404459,3.611235,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
40,000623.SZ,20.190515,6.931092,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
41,000625.SZ,61.194249,9.165211,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
42,000627.SZ,23.757924,3.509614,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
43,000629.SZ,5.405783,8.562599,10,3246,928,464,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
44,000630.SZ,2.855609,2.548604,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
45,000651.SZ,8.917773,2.855990,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
46,000656.SZ,7.281997,7.175214,10,3332,952,476,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
47,000661.SZ,20.207346,33.526779,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
48,000671.SZ,5.139101,5.897800,10,3468,991,496,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
49,000686.SZ,2.590696,2.159213,10,3495,998,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
50,000703.SZ,38.072605,92.105295,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
51,000708.SZ,7.661802,7.965549,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
52,000709.SZ,7.428602,4.302260,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
53,000712.SZ,29.908856,77.102323,10,3414,976,488,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
54,000718.SZ,10.020230,21.356298,10,3392,970,485,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
55,000723.SZ,52.877635,229.470432,10,3273,936,468,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
56,000725.SZ,11.487575,48.292935,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
57,000728.SZ,94.124335,14.018512,10,3450,986,493,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
58,000729.SZ,1.965414,2.581107,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN
59,000738.SZ,3.677316,2.703042,10,3497,999,500,simple_stacked_lstm_stock_1,NaN,NaN,NaN,NaN,NaN

## Display File 2

In [ ]:
display_file = "training_log/sm_ma_gc_30win.csv"

fileDir = os.path.dirname(os.path.realpath('__file__'))
filename = os.path.join(fileDir, display_file)
df_2 = pd.read_csv(filename)

In [ ]:
display(df_2)